### ISSUE TITLE
Data Binding annotation processor version

### ISSUE THREAD

**Issue by ghost** [instamobile/kotlin-firebase#1]
Data Binding annotation processor version needs to match the Android Gradle Plugin version. You can remove the kapt dependency androidx.databinding:databinding-compiler:4.1.3 and Android Gradle Plugin will inject the right version.
Affected Modules: app

**Comment by KHirgeto** [comment]
> Data Binding annotation processor version needs to match the Android Gradle Plugin version. You can remove the kapt dependency androidx.databinding:databinding-compiler:4.1.3 and Android Gradle Plugin will inject the right version.
> Affected Modules: app
